name: Docker Base Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'base.Dockerfile'
      - '**/docker-base-image.yml'

jobs:
  build_and_push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag buildtools-optsrv:base --file base.Dockerfile .
    - name: Login to Docker Hub
      shell: cmd
      run: docker login -u devatkc -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag the Docker image
      run: docker tag buildtools-optsrv:base devatkc/buildtools-optsrv:base
    - name: Push the Docker image
      run: docker push devatkc/buildtools-optsrv:base
    - name: Logout from Docker Hub
      run: docker logout
